# Helper configuration for local development.
version: '3'

volumes:
  postgres_data:
  consul_data:
  etcd:

services:
  consul:
      image: consul:1.4.0
      ports:
        - 8500:8500
      volumes:
        - consul_data:/consul/data
  postgres:
      image: postgres:11-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: jboss/keycloak:4.8.3.Final
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.11
    ports:
      - 2379:2379
    volumes:
      - etcd:/etcd_data
    command:
      - /usr/local/bin/etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379